
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cezuzgiertgqomiyujzm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNlenV6Z2llcnRncW9taXl1anptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzNTY3MjIsImV4cCI6MjA1OTkzMjcyMn0.w-CnkVacHnZueDwfCnFo1odiANdnu8u3JaV4xl6nqdk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
